name: platform_ocr
description: A high-performance, local OCR package for Dart and Flutter that leverages native OS APIs.
version: 1.0.0
homepage: https://github.com/kikuchy/platform_ocr
repository: https://github.com/kikuchy/platform_ocr

platforms:
  ios:
  macos:
  windows:

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  code_assets: ^0.19.10
  objective_c: ^9.2.2
  native_toolchain_c: ^0.17.2
  hooks: ^0.20.5
  ffi: ^2.1.2
  image: ^4.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  ffigen: ^20.1.1
  native_assets_cli: ^0.10.0
  logging: ^1.3.0
