name: platform_ocr
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  code_assets:
  objective_c: ^9.2.2
  native_toolchain_c:
  hooks:
  ffi: ^2.1.2
  image: ^4.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  ffigen: ^20.1.1
  native_assets_cli: ^0.10.0
  logging: ^1.3.0
